queries:
  sql-statement: |
    SELECT
      t.id,
      t.dateof,
      sender.account_name AS sender_name,
      receiver.account_name AS receiver_name,
      t.amount,
      a.asset_name AS unit,
      GROUP_CONCAT(
        CASE
          WHEN tg.category = 'MCC' THEN tg.tag_name
          ELSE NULL
        END
      ) AS MCC,
      GROUP_CONCAT(
        CASE
          WHEN tg.category <> 'MCC' AND tg.tag_name NOT GLOB '*[0-9]*' THEN tg.tag_name
          ELSE NULL
        END
      ) AS tag_names,
      t.description,
      sender.account_owner AS snd_owner,
      receiver.account_owner AS rec_owner,
      t.report
    FROM
      transactions t
    JOIN
      accounts sender ON t.sender = sender.id
    JOIN
      accounts receiver ON t.receiver = receiver.id
    JOIN
      assets a ON t.unit = a.id
    LEFT JOIN
      transaction_tags tt ON t.id = tt.id
    LEFT JOIN
      tags tg ON tt.tag_id = tg.id
    WHERE
      a.asset_type = 'currency'
    GROUP BY
      t.id, t.dateof, sender_name, receiver_name, t.amount, unit
    ORDER BY
      t.id;
  sql-statement1: |
    SELECT
      t.id,
      t.dateof,
      sender.account_name AS sender_name,
      receiver.account_name AS receiver_name,
      t.amount,
      a.asset_name AS unit,
      GROUP_CONCAT(
        CASE
          WHEN tg.category = 'MCC' THEN tg.tag_name
          ELSE NULL
        END
      ) AS MCC,
      GROUP_CONCAT(
        CASE
          WHEN tg.category <> 'MCC' AND tg.tag_name NOT GLOB '*[0-9]*' THEN tg.tag_name
          ELSE NULL
        END
      ) AS tag_names,
      t.description,
      sender.account_owner AS snd_owner,
      receiver.account_owner AS rec_owner,
      t.report
    FROM
      transactions t
    JOIN
      accounts sender ON t.sender = sender.id
    JOIN
      accounts receiver ON t.receiver = receiver.id
    JOIN
      assets a ON t.unit = a.id
    LEFT JOIN
      transaction_tags tt ON t.id = tt.id
    LEFT JOIN
      tags tg ON tt.tag_id = tg.id
    WHERE
      a.asset_type = 'currency'
    GROUP BY
      t.id, t.dateof, sender_name, receiver_name, t.amount, unit
    ORDER BY
      t.id;
  sql-statement2: |
    SELECT
      t.id,
      t.dateof,
      sender.account_name AS sender_name,
      receiver.account_name AS receiver_name,
      t.amount,
      a.asset_name AS unit,
      GROUP_CONCAT(
        CASE
          WHEN tg.category = 'MCC' THEN tg.tag_name
          ELSE NULL
        END
      ) AS MCC,
      GROUP_CONCAT(
        CASE
          WHEN tg.category <> 'MCC' AND tg.tag_name NOT GLOB '*[0-9]*' THEN tg.tag_name
          ELSE NULL
        END
      ) AS tag_names,
      t.description,
      sender.account_owner AS snd_owner,
      receiver.account_owner AS rec_owner,
      t.report
    FROM
      transactions t
    JOIN
      accounts sender ON t.sender = sender.id
    JOIN
      accounts receiver ON t.receiver = receiver.id
    JOIN
      assets a ON t.unit = a.id
    LEFT JOIN
      transaction_tags tt ON t.id = tt.id
    LEFT JOIN
      tags tg ON tt.tag_id = tg.id
    WHERE
      a.asset_type = 'currency'
    GROUP BY
      t.id, t.dateof, sender_name, receiver_name, t.amount, unit
    ORDER BY
      t.id;
  sql-statement3: |
    SELECT
      t.id,
      t.dateof,
      sender.account_name AS sender_name,
      receiver.account_name AS receiver_name,
      t.amount,
      a.asset_name AS unit,
      GROUP_CONCAT(
        CASE
          WHEN tg.category = 'MCC' THEN tg.tag_name
          ELSE NULL
        END
      ) AS MCC,
      GROUP_CONCAT(
        CASE
          WHEN tg.category <> 'MCC' AND tg.tag_name NOT GLOB '*[0-9]*' THEN tg.tag_name
          ELSE NULL
        END
      ) AS tag_names,
      t.description,
      sender.account_owner AS snd_owner,
      receiver.account_owner AS rec_owner,
      t.report
    FROM
      transactions t
    JOIN
      accounts sender ON t.sender = sender.id
    JOIN
      accounts receiver ON t.receiver = receiver.id
    JOIN
      assets a ON t.unit = a.id
    LEFT JOIN
      transaction_tags tt ON t.id = tt.id
    LEFT JOIN
      tags tg ON tt.tag_id = tg.id
    WHERE
      a.asset_type = 'currency'
    GROUP BY
      t.id, t.dateof, sender_name, receiver_name, t.amount, unit
    ORDER BY
      t.id;
